from pathlib import Path
import sympy as sp

from qedcalc.parser.qed_latex import parse_loop_integral_latex
from qedcalc.operations.ladder import (
    analyze_raw_ordinary_ladder,
    ladder_general_q_projector_result,
    load_ladder_coefficient_table,
    compare_ladder_integral_tables,
    write_ladder_general_q_integral_table_csv,
    LadderIntegralIndex,
)

ROOT = Path(__file__).parents[1]
source = (ROOT / 'input' / 'ordinary_ladder_2loop_bare.tex').read_text(encoding='utf-8')
raw = analyze_raw_ordinary_ladder(parse_loop_integral_latex(source))
reference = load_ladder_coefficient_table(ROOT / 'data' / 'ladder_Ddim_75_coefficients.csv')

archived = ladder_general_q_projector_result(raw, 'archived')
corrected = ladder_general_q_projector_result(raw, 'spin_sum')
diff_archived = compare_ladder_integral_tables(archived.integral_table, reference)
diff_corrected = compare_ladder_integral_tables(corrected.integral_table, reference)

csv_archived = write_ladder_general_q_integral_table_csv(
    archived.integral_table, ROOT / 'output' / 'ladder_general_q_75_coefficients_generated.csv'
)
csv_corrected = write_ladder_general_q_integral_table_csv(
    corrected.integral_table, ROOT / 'output' / 'ladder_general_q_corrected_spin_sum_generated.csv'
)

D, z = sp.symbols('D z')
representatives = [
    LadderIntegralIndex(1,1,0,1,1,1,1),
    LadderIntegralIndex(1,0,-1,1,1,1,1),
    LadderIntegralIndex(0,0,-1,1,1,1,1),
    LadderIntegralIndex(1,1,0,0,0,0,1),
]

lines = []
lines += ['# Ordinary ladder general-q raw projector trial', '']
lines += ['This file is generated by QEDCalc from the bare ordinary-ladder LaTeX input.', '']
lines += ['## Purpose', '']
lines += ['The ordinary-ladder archive contains a 75-term general-$q^2$ coefficient table. Later auditing of the derivation identified that this table was generated with the historical projector-first trace ordering. QEDCalc now reproduces that table from the raw bare expression and keeps it explicitly separate from the corrected spin-sum trace ordering.', '']
lines += ['## Historical archived trace ordering', '']
lines += ['The archived table uses', '']
lines += ['$$', r'\operatorname{Tr}\left[(\rlap{/}p\prime+m)O_\mu(\rlap{/}p+m)\Gamma_{\mathrm L}^{\mu}\right]', '$$', '']
lines += [f'Generated scalar-integral monomials: **{len(archived.integral_table)}**', '']
lines += [f'Missing indices versus archived CSV: **{len(diff_archived["missing"])}**', '']
lines += [f'Extra indices versus archived CSV: **{len(diff_archived["extra"])}**', '']
lines += [f'Coefficient mismatches versus archived CSV: **{len(diff_archived["mismatched"])}**', '']
lines += ['Therefore the raw regeneration matches the archived 75-term CSV exactly.', '']
lines += ['### Representative regenerated coefficients', '']
lines += ['| Integral index | Regenerated coefficient | Archived coefficient |', '|---|---|---|']
for idx in representatives:
    g = sp.factor(archived.integral_table[idx])
    r = sp.factor(reference[idx])
    lines += [f'| `{idx.as_tuple()}` | `${sp.latex(g)}$` | `${sp.latex(r)}$` |']
lines += ['', f'Generated CSV: `{csv_archived.relative_to(ROOT)}`', '']

lines += ['## Corrected spin-sum trace ordering', '']
lines += ['The audited physical spin-sum ordering is', '']
lines += ['$$', r'\operatorname{Tr}\left[(\rlap{/}p\prime+m)\Gamma_{\mathrm L}^{\mu}(\rlap{/}p+m)O_\mu\right]', '$$', '']
lines += [f'Generated scalar-integral monomials: **{len(corrected.integral_table)}**', '']
lines += [f'Missing archived indices: **{len(diff_corrected["missing"])}**', '']
lines += [f'Extra indices: **{len(diff_corrected["extra"])}**', '']
lines += [f'Coefficient mismatches on common indices: **{len(diff_corrected["mismatched"])}**', '']
lines += ['This result is intentionally not forced to match the historical 75-term CSV. The two trace conventions are stored as separate routes so a historical audit table cannot silently replace the corrected physical projector route.', '']
lines += [f'Corrected-route CSV: `{csv_corrected.relative_to(ROOT)}`', '']

lines += ['## Automation boundary', '']
lines += ['The archived 75-term general-$q^2$ coefficient table is now regenerated completely from the raw bare ladder expression. The remaining major ordinary-ladder automation gap is a general IBP/Laporta reducer. For the physical $F_2(0)$ derivation QEDCalc continues to use the audited finite-limit $A_0$ and $C_1=B_1-2A_1$ route rather than treating the historical 75-term audit table as the final projector.', '']

(ROOT / 'output' / 'ladder_general_q_raw_trace_trial.md').write_text('\n'.join(lines), encoding='utf-8')
print(f'Archived table regenerated: {len(archived.integral_table)} terms')
print(f'Archived CSV exact match: {diff_archived == {"missing": [], "extra": [], "mismatched": []}}')
print(f'Corrected spin-sum table: {len(corrected.integral_table)} terms')
