from pathlib import Path
import sympy as sp
from qedcalc.parser.qed_latex import parse_loop_integral_latex
from qedcalc.operations.ladder import (
    analyze_raw_ordinary_ladder,
    ladder_a0_projector_trace_sympy,
    ladder_a0_denominator_polynomial,
    ladder_a0_integral_table,
    write_ladder_a0_integral_table_csv,
)

ROOT=Path(__file__).parents[1]
source=(ROOT/'input'/'ordinary_ladder_2loop_bare.tex').read_text(encoding='utf-8')
diagram=parse_loop_integral_latex(source)
raw=analyze_raw_ordinary_ladder(diagram)
trace=ladder_a0_projector_trace_sympy(raw)
poly=ladder_a0_denominator_polynomial(raw)
table=ladder_a0_integral_table(raw)
csv_path=write_ladder_a0_integral_table_csv(table,ROOT/'output'/'ladder_A0_29_coefficients_generated.csv')

lines=[]
lines += ['# Ordinary ladder raw A0 trace trial','']
lines += ['This file is generated by QEDCalc from the bare ordinary-ladder LaTeX input.','']
lines += ['## Raw A0 projector trace','']
lines += ['The program constructs','']
lines += ['$$',r'A_0=\operatorname{Tr}\left[(\rlap{/}P+m)N_\mu^{(0)}(\rlap{/}P+m)\gamma^\mu\right]','$$','']
lines += ['and evaluates the arbitrary-length $D$-dimensional Clifford trace using the optimized fully-contracted trace engine.','']
lines += ['## Denominator polynomial','']
lines += ['After imposing $P^2=m^2$ and replacing scalar products by the $K,L,H,A,B$ denominator basis, QEDCalc obtains','']
lines += ['$$',sp.latex(sp.factor(poly)),'$$','']
lines += ['## Integral-family result','']
lines += [f'Number of distinct scalar integrals: **{len(table)}**','']
lines += ['The q=0 denominator is $KLA^2B^2$; numerator monomials are converted to $J(n_K,n_L,n_H,n_A,n_B)$.','']
lines += ['| Integral index | Coefficient |','|---|---|']
for idx,coeff in table.items():
    lines += [f'| `{idx.as_tuple()}` | `${sp.latex(sp.factor(coeff))}$ |']
lines += ['','Generated CSV: `output/ladder_A0_29_coefficients_generated.csv`','']
lines += ['## Automation boundary','']
lines += ['The complete $A_0$ 29-integral table is now regenerated from the raw bare ladder expression. The remaining ordinary-ladder gap is the general-$q^2$ Pauli-projector branch that generates the 75-term audit table, followed by a general IBP/Laporta reducer.','']
(ROOT/'output'/'ladder_A0_raw_trace_trial.md').write_text('\n'.join(lines),encoding='utf-8')
print(f'A0 integrals generated: {len(table)}')
print(f'CSV: {csv_path}')
