from pathlib import Path
import sympy as sp

from qedcalc import parse_loop_integral_latex, render_latex
from qedcalc.operations.ladder import (
    ladder_projector_coefficients, ladder_scalar_product_rules,
    load_ladder_coefficient_table, ladder_coefficient,
    one_loop_f2_dimensional, one_loop_z1_dimensional,
    ladder_subtraction_series, ladder_bare_checkpoint,
    ladder_renormalized_checkpoint, analyze_raw_ordinary_ladder,
    derive_ladder_scalar_product_rules_from_family, raw_ladder_q0_numerator,
)

ROOT=Path(__file__).parents[1]
OUT=ROOT/'output'/'ladder_2loop_trial.md'
CSV=ROOT/'data'/'ladder_Ddim_75_coefficients.csv'
D,z,delta=sp.symbols('D z delta')

def math(tex):
    return f"\n$$\n{tex}\n$$\n"

lines=[]
lines.append('# QEDCalc two-loop ordinary-ladder trial\n')
lines.append('This trial uses the supplied ordinary-ladder derivation as the checkpoint source. It does not yet regenerate all 75 coefficients from the raw D-dimensional Dirac trace.\n')

RAW=ROOT/'input'/'ordinary_ladder_2loop_bare.tex'

raw_source=RAW.read_text(encoding='utf-8')
raw_diagram=parse_loop_integral_latex(raw_source)
raw_info=analyze_raw_ordinary_ladder(raw_diagram)
lines.append('## 0. Raw bare two-loop LaTeX bridge\n')
lines.append('The ordinary-ladder RHS is parsed as one symbolic-D two-loop expression. QEDCalc detects the four ordered electron propagators and the two photon denominators before using any stored 75-term coefficient table.\n')
lines.append(math(r'\Lambda_{\mu,\mathrm L}^{(2)}\;\text{raw input}='+render_latex(raw_diagram)))
for label,mom in zip(raw_info.electron_labels,raw_info.electron_momenta):
    pretty=label[0]+'_{'+label[1:]+'}'
    lines.append(math(pretty+r'\;\longleftrightarrow\;'+render_latex(mom)))
lines.append(math(r'J_{\rm bare}=J'+str(raw_info.base_integral_index.as_tuple()).replace(' ','')))
lines.append('The auxiliary denominator is introduced with exponent zero in the bare graph so numerator powers generated by the projector can be represented in the same family.\n')
lines.append(math(r'H=-(k+l)^2'))
lines.append('### Scalar-product basis derived from the denominator definitions\n')
for lhs,rhs in derive_ladder_scalar_product_rules_from_family().items():
    lines.append(math(sp.latex(lhs)+r'='+sp.latex(rhs)))
lines.append('### Direct q=0 Dirac numerator generated from the raw graph\n')
lines.append(math(r'N_{\mu}^{(0)}='+render_latex(raw_ladder_q0_numerator(raw_info))))

a,b=ladder_projector_coefficients(D,z)
lines.append('## 1. D-dimensional Pauli projector coefficients\n')
lines.append(math(r'a='+sp.latex(a)))
lines.append(math(r'b='+sp.latex(b)))

lines.append('## 2. Scalar-product to denominator rules\n')
for lhs,rhs in ladder_scalar_product_rules().items():
    lines.append(math(sp.latex(lhs)+r'='+sp.latex(rhs)))

table=load_ladder_coefficient_table(CSV)
lines.append('## 3. Reproducible 75-term integral-family table\n')
lines.append(f'Loaded monomials: **{len(table)}**.\n')
checks=[
    ((1,1,0,1,1,1,1),'C_{1,1,0,1,1,1,1}'),
    ((1,0,-1,1,1,1,1),'C_{1,0,-1,1,1,1,1}'),
    ((0,0,-1,1,1,1,1),'C_{0,0,-1,1,1,1,1}'),
    ((1,0,-1,1,1,1,0),'C_{1,0,-1,1,1,1,0}'),
    ((1,1,0,0,0,0,1),'C_{1,1,0,0,0,0,1}'),
    ((1,1,0,0,1,-1,1),'C_{1,1,0,0,1,-1,1}'),
]
for idx,name in checks:
    lines.append(math(name+'='+sp.latex(ladder_coefficient(table,*idx))))

lines.append('## 4. D-dimensional one-loop subtraction ingredients\n')
lines.append(math(r'F_2^{(1l)}(D,0)='+sp.latex(one_loop_f2_dimensional(D))))
lines.append(math(r'Z_1^{(1l)}='+sp.latex(one_loop_z1_dimensional(D))))
sub=ladder_subtraction_series(delta,1)
lines.append(math(r'F_{2,\mathrm{sub}}^{(2)}(0)='+sp.latex(sub)))

lines.append('## 5. Bare checkpoint and UV subtraction\n')
bare=ladder_bare_checkpoint(delta)
final=ladder_renormalized_checkpoint(delta)
lines.append(math(r'F_{2,\mathrm L}^{\mathrm{bare}}='+sp.latex(bare)+r'+O(\delta)'))
lines.append(math(r'F_{2,\mathrm L}^{\mathrm R}(0)='+sp.latex(final)))
lines.append(math(r'F_{2,\mathrm L}^{(4)}(0)=\left(\frac{\alpha}{\pi}\right)^2\left['+sp.latex(final)+r'\right]'))

lines.append('## 6. Automation boundary\n')
lines.append('QEDCalc now parses the raw symbolic-D two-loop ladder RHS, detects E1..E4 and K,L, constructs the seven-denominator family including auxiliary H, derives the scalar-product basis from the denominator equations, and then automates the stored coefficient-table validation and D-dimensional subtraction. The q=0 A0 branch is now regenerated separately from the raw D-dimensional projector trace into 29 scalar integrals (see run_ladder_a0_trace_demo.bat). The historical general-q^2 75-term audit table is now regenerated from the raw projector trace. v0.27.0 also provides a generic IBP generator and finite sparse Laporta eliminator. The remaining step is complete seed closure/sector handling and master-integral reduction for the seven-denominator family.\n')

OUT.write_text('\n'.join(lines),encoding='utf-8')
print(f'Wrote: {OUT}')
print('Loaded coefficient monomials:',len(table))
print('Renormalized ladder coefficient:',final)
