from pathlib import Path
from qedcalc.operations.crossed_ladder import crossed_v_partial_fraction_checks
ROOT=Path(__file__).resolve().parents[1]
c=crossed_v_partial_fraction_checks()
assert c['sample_differences']==(0,0,0)
assert c['log_coefficient']==0
assert c['h_log_argument_difference']==0
lines=[
 '# Phase 22: crossed-ladder V partial-fraction bridge','',
 'The six coefficients A4,A3,A2,A1,B2,B1 are generated by coefficient comparison rather than a general apart() call.','',
 'Exact rational sample reconstruction checks: **PASS**.','',
 'The simple-pole logarithmic coefficient is','',
 '$$',r'\frac{A_1}{R+U}+\frac{B_1}{R^2}=0.','$$','',
 'After h=S(R+U)-1, the generated logarithm argument is','',
 '$$',r'\frac{(h+1)\left[h+(R-1)^2\right]}{hR^2}.','$$','',
 'This matches the independent detailed derivation exactly.',''
]
(ROOT/'output'/'phase22_crossed_v_bridge_trial.md').write_text('\n'.join(lines),encoding='utf-8')
print('Phase-22 crossed V bridge: PASS')
