from __future__ import annotations

from dataclasses import dataclass
import sympy as sp


@dataclass(frozen=True)
class CornerSectorResult:
    """Analytic sector bookkeeping for the two-loop corner (IIc) contribution."""
    hard_primary: sp.Expr
    shift_correction: sp.Expr
    hard_total: sp.Expr
    z_sector: sp.Expr
    finite_total: sp.Expr


@dataclass(frozen=True)
class CornerIRCancellation:
    """IR-log bookkeeping between corner IIc and the self-energy insertion pair."""
    corner_log_coefficient: sp.Expr
    self_energy_log_coefficient: sp.Expr
    total_log_coefficient: sp.Expr
    combined_finite: sp.Expr


def corner_soft_kernel(U=None, R=None, S=None, v=None):
    """Leading physical-measure soft kernel after u=rho*U, a_d=u*R, a_p=u*S.

    This is the rho^0 soft kernel of the UV-finite corner parameter representation.
    """
    U = sp.Symbol("U", positive=True) if U is None else sp.sympify(U)
    R = sp.Symbol("R", positive=True) if R is None else sp.sympify(R)
    S = sp.Symbol("S", positive=True) if S is None else sp.sympify(S)
    v = sp.Symbol("v", positive=True) if v is None else sp.sympify(v)
    return sp.simplify(
        2*R*S*U*v*(4*R + S + 4*v)
        / ((R+v)**2 * (1+U**2) * (R+S+v)**4)
    )


def corner_soft_spatial_kernel(R=None, S=None, v=None):
    """Soft kernel with the universal U/(1+U^2) factor removed."""
    R = sp.Symbol("R", positive=True) if R is None else sp.sympify(R)
    S = sp.Symbol("S", positive=True) if S is None else sp.sympify(S)
    v = sp.Symbol("v", positive=True) if v is None else sp.sympify(v)
    return sp.simplify(2*R*S*v*(4*R + S + 4*v) / ((R+v)**2*(R+S+v)**4))


def corner_soft_integrate_S(R=None, v=None):
    """Analytic S integral of the spatial soft kernel."""
    R = sp.Symbol("R", positive=True) if R is None else sp.sympify(R)
    v = sp.Symbol("v", positive=True) if v is None else sp.sympify(v)
    return sp.simplify(2*R*v/(R+v)**3)


def corner_soft_integrate_R(v=None):
    """Analytic R integral after the S integration."""
    v = sp.Symbol("v", positive=True) if v is None else sp.sympify(v)
    return sp.Integer(1)


def corner_soft_ir_coefficient():
    """Exact coefficient of log(1/rho) in the corner contribution."""
    return sp.Integer(1)


def corner_shifted_p_minus_k(u=None, v=None):
    """Return coefficients of p', p'', and k after the common loop-momentum shift.

    p' - k -> (1-u*v) p' - u(1-v) p'' - k.
    """
    u = sp.Symbol("u") if u is None else sp.sympify(u)
    v = sp.Symbol("v") if v is None else sp.sympify(v)
    return {
        "p_prime": sp.expand(1-u*v),
        "p_double_prime": sp.expand(-u*(1-v)),
        "k": sp.Integer(-1),
    }


def corner_hard_primary_result():
    """First K+kappa^2 hard-sector integral group."""
    return sp.simplify(
        -sp.Rational(19,3)
        -sp.Rational(15,8)*sp.zeta(3)
        +sp.Rational(11,36)*sp.pi**2
        +sp.Rational(3,4)*sp.pi**2*sp.log(2)
    )


def corner_shift_correction_result():
    """Additional hard-sector contribution generated by the correct momentum shift."""
    return sp.simplify(
        sp.Rational(8,3)
        -sp.pi**2/4
        -sp.pi**2*sp.log(2)/6
        +sp.Rational(3,4)*sp.zeta(3)
    )


def corner_hard_total_result():
    """Complete K+kappa^2 hard sector."""
    return sp.simplify(corner_hard_primary_result() + corner_shift_correction_result())


def corner_z_sector_result():
    """Analytic z-sector contribution."""
    return sp.simplify(
        sp.Rational(7,8)
        +sp.Rational(5,8)*sp.zeta(3)
        -sp.pi**2*sp.log(2)/4
    )


def corner_sector_result() -> CornerSectorResult:
    hard1 = corner_hard_primary_result()
    shift = corner_shift_correction_result()
    hard = sp.simplify(hard1 + shift)
    z = corner_z_sector_result()
    finite = sp.simplify(hard + z)
    return CornerSectorResult(hard1, shift, hard, z, finite)


def corner_finite_result():
    """Finite part A_C,fin of the two-loop corner contribution."""
    return corner_sector_result().finite_total


def corner_expected_finite_result():
    """Independent closed-form checkpoint from the completed derivation."""
    return sp.simplify(
        -sp.Rational(67,24)
        +sp.pi**2/18
        -sp.zeta(3)/2
        +sp.pi**2*sp.log(2)/3
    )


def corner_result_difference():
    return sp.simplify(corner_finite_result() - corner_expected_finite_result())


def corner_full_asymptotic(rho=None):
    """A_C(rho) through the finite term, omitting o(1)."""
    rho = sp.Symbol("rho", positive=True) if rho is None else sp.sympify(rho)
    return sp.simplify(sp.log(1/rho) + corner_finite_result())


def self_energy_insertion_asymptotic(rho=None):
    """Self-energy insertion pair used for the explicit IR cancellation check."""
    rho = sp.Symbol("rho", positive=True) if rho is None else sp.sympify(rho)
    return sp.simplify(-sp.log(1/rho) + sp.Rational(11,24) - sp.pi**2/18)


def corner_self_energy_ir_cancellation() -> CornerIRCancellation:
    """Return exact cancellation data for corner IIc + self-energy insertion pair."""
    c = sp.Integer(1)
    s = sp.Integer(-1)
    combined_finite = sp.simplify(
        corner_finite_result() + sp.Rational(11,24) - sp.pi**2/18
    )
    return CornerIRCancellation(c, s, sp.simplify(c+s), combined_finite)


def recognize_corner_constant(value, precision=80):
    """Recognize a numeric value in the corner finite-part basis."""
    value = sp.N(value, precision)
    return sp.nsimplify(
        value,
        [sp.pi**2, sp.zeta(3), sp.pi**2*sp.log(2)],
        full=True,
    )


def corner_soft_finite_constant():
    """Finite constant of the leading soft region.

    This is a diagnostic/matching quantity. It is already encoded in the global
    hard-subtracted bookkeeping and must not be added again to A_C,fin.
    """
    return sp.simplify(sp.pi**2/6 + sp.log(2)**2 - 3*sp.log(2) - sp.Rational(7,4))


def corner_hard_remainder_from_soft_split():
    """Hard remainder in the diagnostic split A_C,fin=C_soft+H_fin."""
    return sp.simplify(corner_finite_result() - corner_soft_finite_constant())


def corner_soft_hard_split_difference():
    """Exact check of the diagnostic soft+hard split."""
    return sp.simplify(
        corner_soft_finite_constant()
        + corner_hard_remainder_from_soft_split()
        - corner_finite_result()
    )
